### PR TITLE
feat(extension): create vite react app

### PR DESCRIPTION
**Pull request by MjxOro**
# Summary
- Set up the front end of the Chrome extension using Vite 3 to set up a react app with typescript.

### CODE REVIEW

**Review by hyunchol-launchup-s — APPROVED** [review]
Great work setting up the extension!

**Review by YoussefLaunchUp — CHANGES_REQUESTED** [review]
Please add Documentation for this addition.

**Review by YoussefLaunchUp — APPROVED** [review]
Great Work

**Review by hyunchol-jun — APPROVED** [review]
Nice work!

**Pull request merged**
