### PR TITLE
feat(FOC-9): set up backend server

### PR DESCRIPTION
**Pull request by hyunchol-jun**
## Description

- Set up backend server with nest.js to be developed with TypeScript.
- Created Graphql apis for CRUD operations on User entity.

## Test instructions

To run it locally,
- Run `npm i` to install dependencies.
- Run `npm start` or `npm run start:dev`(watch mode).
- Visit `localhost:3000/graphql` to test APIs in the playground.

#### Get User
```
query {
  user(userId: 2) {
    userId
    email
  }
}
```

#### Create User
```
mutation {
  createUser(createUserData: {email: "test1@example.com"}) {
    userId
    email
  }
}
```

#### Update User
```
mutation {
  updateUser(updateUserData: {userId:2, email: "test2@example.com"}) {
    userId
    email
  }
}
```

#### Delete User
```
mutation {
  deleteUser(deleteUserData: {userId: 1}) {
    userId
    email
  }
}
```

### CODE REVIEW

**Review by MjxOro — APPROVED** [review]
LGTM

**Review by YoussefLaunchUp — CHANGES_REQUESTED** [review]
Please change to Graphql instead of rest (tests need to be changed as well)

**Comment by hyunchol-jun** [comment]
Updated to have Graphql apis instead of REST. Old e2e test for REST has been deleted.

**Review by YoussefLaunchUp — APPROVED** [review]
Good work!

**Pull request merged**
